## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here,
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [9]:
A=[[3,1,2],[-5,4,1],[0,3,-8]]
B=[[0,5,-1],[3,2,-1],[10,0.5,4]]
n_A=np.array(A)
n_B=np.array(B)
C1=np.dot(n_A,n_B)
C2=np.dot(n_B,n_A)
print(C1,C1[1][2])
print(C2,C2[1][2])

[[ 23.   18.    4. ]
 [ 22.  -16.5   5. ]
 [-71.    2.  -35. ]] 5.0
[[-25.   17.   13. ]
 [ -1.    8.   16. ]
 [ 27.5  24.  -11.5]] 16.0


In [ ]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    return ""

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [19]:
A2=np.array([[3,0.6,4,-3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B2=np.array([[3,-5.76,45,0],[2,-2,1.3,9],[9,0,0,0]])
C2=np.array([[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]])


In [21]:
D=A2+B2-C2
print(D,D[1][2])
print(D[2][0])

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 2.370000e+01  0.000000e+00 -8.000000e+00  6.000000e-03]] -2.7
23.7


In [ ]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [31]:

A3=np.array([0.6,-15,2,5,98])
B3=np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])
C3=np.dot(A3,B3)
print(C3)
dim=np.shape(C3)
print(dim)
row=dim[0]
col=1
#col=dim[1]
print(f"no. of rows={row},no. of columns={col},C13={C3[2]}")

[-102.8  255.2  595.6]
(3,)
no. of rows=3,no. of columns=1,C13=595.6
